apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: lgtm
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024

      resource:
        attributes:
          - key: service.name
            action: upsert
            value: demo-app

    exporters:
      otlphttp/tempo:
        endpoint: http://tempo.lgtm.svc.cluster.local:4318
        tls:
          insecure: true

      prometheusremotewrite:
        endpoint: http://mimir-gateway.lgtm.svc:80/api/v1/push
        tls:
          insecure: true

      loki:
        endpoint: http://loki-gateway.lgtm.svc.cluster.local/loki/api/v1/push
        tls:
          insecure: true

      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [otlphttp/tempo, logging]

        metrics:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [prometheusremotewrite, logging]

        logs:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [loki, logging]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: lgtm
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.96.0
          args:
            - --config=/conf/config.yaml
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
